### ISSUE TITLE
build failed with electron-vue

### ISSUE THREAD

**Issue by TinkoLiu** [joeistas/node-casclib#1]
When using with electron-vue, native dependency will build failed.
Error reports error: unknown type name 'napi_deferred'
I think it's just not includes the node-addon-api correctly but don't know how to fix it.

Note: I found this problem could solved by copying `~/.node-gyp/{{version}}/include` to `~/.electron-gyp/iojs-{{iojs_version}}/include`, but still curious about this.

**Comment by joeistas** [comment]
For this addon I used a newer node API, N-API it is only supported on newer versions of node (currently 8.x and 9.x). electron-vue looks to be currently using version 1.7.x of electron which doesn't support N-API. It looks like electron 1.8.x and higher supports N-API so if you upgrade to a newer version of electron, it should fix your issue.

**Comment by TinkoLiu** [comment]
Got it.
My global environment is Node v8.10.0, yarn 1.5.1, Electron 1.8.4.
However, the Electron in my project environment is 1.7.5.
But I got the module built correctly by copying the `include` folder, and it worked fine both in dev mode and packaged built standalone executable :D 
Closing this issue, thanks. @joeistas
